name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        docker tag my-image-name:$(date +%s) ${{ secrets.DOCKER_HUB_USERNAME }}/my-image-name:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-image-name:latest
